version: "3.7"
services:
  global-store-bk:
    container_name: global-store-bk
    image: global-store-bk:v1
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    networks:
      - global-store-app
networks: 
  global-store-app:
  
  
